language: c
dist: xenial
os:
- linux
- osx
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f /usr/local/include/c++ ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mlkit ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y mlton make ;
  fi
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make clean all bin_dist ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MLCOMP=mlton make clean all bin_dist
  ; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make test ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MLCOMP=mlton make test ; fi
deploy:
  provider: releases
  api_key:
    secure: JZhcDZnR5gnmWUtWHOaxLuzR+YARs1MEjKsEuvTmqgaqXe5SylicPEDXgZD9MJAmPgkOVa3r3e6t+Ni7dt1rjiSw8FoTpvP3fAg+CQsPHOYta1/SW229H25PW73qWxZjx/VfCPry2Rwe7NbKUVLjYDdvTbSYSNcSwtADxYti5Dy2cQa+Gzm219yMCV88UlsFiPWAIMGr6Mq9hYWVGM7srQk+Vc6aOmq0iKvRleJkiFNTy83LfLwb/ym/3mS4otle8VDGy4zMbj38b2E0/JIOHnFcMIV/X1Y06EKEAhvG1Yj9fUYZeGXZ+2yN7Sriw1t5lqTreBTWAeVDLiHDDTPRf9SwHLuQVzUp+/RO7GWg+psxbg1yPnB3QOwApir6fLHv2R7bQBu9aBtpya86gvBBtSGgyDrAW12btqgXFOW2nkBAmd7daU8gjePwhkDN/7SxvrVpReVtQHH7Of18x3Svjw2hnGrOlFjNycpLLavijk5MGMDE8iECr2meFDl39Bf/d8bG/zn5BNV9BDNsefoenPN0BuYqHEjNVJYu2tH1IKHwCURjc7kHz1eAI9YgeWEPr6wPJMfQna8RMVYFasDV6uER7yCMDqvECwS4XtbXTeMKKWZInBF4z9rSfdo+m6g4CwYl6joa11Ys7gNd0g3nA7zE+x65cn/X31djd6kqEEw=
  file_glob: true
  file: smlpkg-bin-dist-*.tgz
  skip_cleanup: true
  on:
    repo: diku-dk/smlpkg
    tags: true
    branch: master